### ISSUE TITLE
This project got excluded from hacktoberfest 2021.

### ISSUE THREAD

**Issue by akash-rajak** [aliya-rahmani/Projects#570]
![image](https://user-images.githubusercontent.com/57003737/137342804-dbdf337b-5e6d-438b-b912-103ae10c03da.png)

**Comment by khan2810** [comment]
@aliya-rahmani why are people doing this kinda things !!! Is there any purpose or profit ?

**Comment by khan2810** [comment]
@akash435 Thanks man !!! you saved me in almost every excluded project.
